apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdid-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdid-api
  template:
    metadata:
      labels:
        app: sdid-api
    spec:
      containers:
        - name: sdid-api
          image: ${IMAGE_WITH_TAG}
          env:
            - name: NODE_ENV
              value: ${NODE_ENV}
            - name: PDF_MODE
              value: ${PDF_MODE}
            - name: REDIS_HOST
              value: redis://sdid-api-services:6379
            - name: PDF_SERVER_URL
              value: http://sdid-api-services:3000
            - name: MONGODB_URI
              value: ${MONGODB_URI}
            - name: JWT_SECRET
              value: ${JWT_SECRET}
            - name: CORS_ORIGIN
              value: ${CORS_ORIGIN}
            - name: HOST
              value: ${HOST}
            - name: MAILER_HOST
              value: ${MAILER_HOST}
            - name: MAILER_PORT
              value: ${MAILER_PORT}
            - name: MAILER_SECURE
              value: ${MAILER_SECURE}
            - name: MAILER_USER
              value: ${MAILER_USER}
            - name: MAILER_PASS
              value: ${MAILER_PASS}
            - name: STRIPE_SECRET_KEY
              value: ${STRIPE_SECRET_KEY}
            - name: STRIPE_WEBHOOK_SECRET
              value: ${STRIPE_WEBHOOK_SECRET}
            - name: STRIPE_SUCCESS_URL
              value: ${STRIPE_SUCCESS_URL}
            - name: STRIPE_CANCEL_URL
              value: ${STRIPE_CANCEL_URL}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdid-api-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdid-api-services
  template:
    metadata:
      labels:
        app: sdid-api-services
    spec:
      containers:
        - name: sdid-api-redis
          image: redis:4-alpine
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent

        - name: sdid-api-pdf-service
          image: paralect/pdf-service
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
