name: dev ci

on:
  push:
    tags:
      - "*.*.*-dev.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/bittlerr/actions-test
          tags: |
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/bittlerr/actions-test
          tags: |
            type=semver,pattern={{version}}

      - name: Subst env vars
        uses: danielr1996/envsubst-action@1.1.0
        env:
          IMAGE_WITH_TAG: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          NODE_ENV: development
          PDF_MODE: ${{ vars.PDF_MODE }}
          CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}
          HOST: ${{ vars.HOST }}
          MAILER_HOST: ${{ vars.MAILER_HOST }}
          MAILER_PORT: ${{ vars.MAILER_PORT }}
          MAILER_SECURE: ${{ vars.MAILER_SECURE }}
          MAILER_USER: ${{ vars.MAILER_USER }}
          STRIPE_SUCCESS_URL: ${{ vars.STRIPE_SUCCESS_URL }}
          STRIPE_CANCEL_URL: ${{ vars.STRIPE_CANCEL_URL }}
          MONGODB_URI: ${{ secrets.MONDODB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MAILER_PASS: ${{ secrets.MAILER_PASS }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        with:
          input: .kube/deployment.yaml
          output: .kube/deployment.yaml

      - name: K3S apply
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONTEXT: default
        with:
          args: apply -f .kube
